#!/usr/bin/env python3
"""Regenerate `_shipped_reference.py` from this repo's own `.supertool.json` (#1783).

The pip route (`py-modules = ["supertool", "_supertool"]`, no packages, no
`MANIFEST.in`) ships neither `.supertool.json` nor `presets/`. Every
declarative route that could carry the file there was tried and rejected --
see #1783's own comment thread:

    package-data with "*"    -- globs over declared *packages*; a flat
                                 py-modules layout has none, so nothing ships
    package-data with ""     -- rejected by setuptools' own schema
    MANIFEST.in +
      include-package-data   -- reaches the sdist, never the wheel
    data-files                -- lands in the venv prefix, not site-packages,
                                 which is where `_shipped_config()` looks

A `.py` module needs none of those routes: it ships exactly because it is
listed in `py-modules` like `_supertool.py` itself. So the reference is
carried as `_shipped_reference.py`, importable on every route including pip,
rather than as another data file.

Only `builtin-ops` is carried, never `.supertool.json` whole. `.supertool.json`
also has an `ops` section -- eight preset-config overrides such as
`{"budget": 1500}` -- that document nothing on their own and describe presets/
the pip route never ships; folding them in would make `help:git-push` render an
empty body and `ops:roster` misreport ops that do not exist on that route.

Run this after editing `.supertool.json`'s `builtin-ops` block:

    python3 .github/scripts/generate_shipped_reference.py

`tests/test_pip_shipped_reference_1783.py::test_generated_reference_is_not_stale`
fails the build if the checked-in file and this script's output ever diverge.
"""
from __future__ import annotations

import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

#: Triple-quote characters as plain strings, built rather than typed literally,
#: so neither this generator source nor its output ever carries a raw
#: triple-quote sequence that would close a delimiter early.
_Q3D = chr(34) * 3
_Q3S = chr(39) * 3

_DOCSTRING = (
    _Q3D + "\n"
    "Generated by .github/scripts/generate_shipped_reference.py -- do not hand-edit.\n"
    "\n"
    "Carries this repo's own `.supertool.json`'s `builtin-ops` block as an\n"
    "importable module, so it ships on the pip route, where no data file\n"
    "survives any declarative packaging option (#1783). `_shipped_config()`\n"
    "falls back to this module only when `.supertool.json` itself is absent\n"
    "beside the running `_supertool.py` -- the clone and plugin routes still\n"
    "read that file directly and never reach this one.\n"
    "\n"
    "Never the whole `.supertool.json`: its `ops` section documents\n"
    "preset-config overrides for presets/ that this route does not ship.\n"
    + _Q3D + "\n"
)

_BODY_HEAD = (
    "from __future__ import annotations\n"
    "\n"
    "import json\n"
    "\n"
    "_BUILTIN_OPS_JSON = r" + _Q3S + "\n"
)
_BODY_TAIL = (
    "\n" + _Q3S + "\n"
    "\n"
    "BUILTIN_OPS = json.loads(_BUILTIN_OPS_JSON)\n"
)


def render() -> str:
    with open(os.path.join(REPO_ROOT, ".supertool.json"), encoding="utf-8") as fh:
        config = json.load(fh)
    builtin_ops = config.get("builtin-ops") or {}
    payload = json.dumps(builtin_ops, indent=2, sort_keys=True)
    return _DOCSTRING + _BODY_HEAD + payload + _BODY_TAIL


def main() -> int:
    out_path = os.path.join(REPO_ROOT, "_shipped_reference.py")
    content = render()
    # `newline="\n"` (#1783 review, oss:auditor): without it, text-mode write
    # translates every newline in `content` to `os.linesep`, so this same
    # generator run on Windows writes CRLF -- invisible on macOS/Linux where
    # `os.linesep` already is a bare newline, and not caught by
    # `test_generated_reference_is_not_stale` either, since that test reads
    # the file back with `Path.read_text()`, which undoes the translation
    # before comparing. Pinning it here makes the file's bytes the same on
    # every platform this generator is ever run from.
    with open(out_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    print(f"wrote {out_path} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
