"""#1635 -- every call in this tree that can remove a *directory*, and who owns it.

A full `pytest` run in a fresh `git clone` was once observed to leave the tree
holding only `tests/` -- `.git` and everything else gone, 603 collection errors
in 14.8s. It has never been reproduced, a reviewer agent was running the suite
in a sibling worktree at the same time, and the mechanism was never established.

This file does not chase that event. It answers the question that is answerable
either way, and keeps it answered:

    which code in this repo can remove a directory it did not create?

**Why an AST walk and not a grep.** This tree mentions `rmtree` and `rm -rf`
constantly. `supertool 'grep:rmtree|rm -rf:.:1'` reports 108 matches over 1092
files at the commit that wrote this line -- and the great majority are prose,
changelog entries, or shell-injection payloads a test asserts are *never*
executed, plus around 25 in this file itself. A count taken from that grep
reads as an inventory and is not one. Only `ast.Call` nodes are sites here,
which is also why the synthetic sources further down are invisible to the
sweep: a call written inside a string literal is an `ast.Constant`, not a call.

**The population, at the commit this was written.** 30 directory-removal sites
across 28 files: 26 `shutil.rmtree`, 2 `subprocess.run(["rm", "-rf", ...])`, 2
`git worktree remove`, and zero `os.rmdir` / `os.removedirs` / `Path.rmdir`.
Only two are outside `tests/` -- `validators/gitleaks/gitleaks.py`, which
removes the private directory it made for one scan, and
`presets/github/pr_merge.py`, the only site in the tree whose path the caller
never composed. Any total written in prose is a measurement of one commit; the
tests below re-derive, and they are what a reader should believe when a number
disagrees with them.

**The verdict, re-derived on every run.** Every one of the 29 sites that
composes its own target resolves to a directory the same file created --
`tempfile.mkdtemp`, a `TemporaryDirectory`, or pytest's `tmp_path`. Not one is
built from the repository root, from the current working directory, or from an
argument the caller does not control. `_supertool.py`, which every op runs
through, contains no directory removal at all. So nothing here explains a
missing `.git`, and that absence is itself the finding: if there was a
mechanism, it is outside the code this file can see.

**Which files count as this repository is not this file's question to answer.**
`tests/_repo_walk.py` already owned it, shared with the spawn guard and the
syntax-floor guard, and the first cut of this register did not use it -- it
carried its own hand-typed list of directory names to skip, which is precisely
the drift that module exists because of (#555, #577, #593). The list was wrong
on its first CI run: `build/` holds Python on a runner and holds none in a
fresh clone, so a skipped-directory check that passed locally failed on
ubuntu. It is not even a property of the runner -- `.gitignore` says `build/`
is "regenerated by the venv-install test (#442), which runs `pip install .`
against the repo root", so the suite creates it *mid-run*, and whether any
given worker saw it depended on test ordering.

The shared walk gets `build/` right without anyone having anticipated it,
because it asks **git** which paths are ignored rather than guessing names
(#449, #575), and falls back to a named artifact floor only when git has no
answer at all -- never reading an unanswered question as a clean sheet (#559).
That also settles the general form of the question: every directory CI
generates is covered, whatever it is called, because the answer is derived at
runtime instead of anticipated.

**One site was missed on the first pass, and how says more than the count.**
`tests/test_branch_worktree_locale_850.py:218` executes a real `git worktree
remove` through a helper that takes the argv words as positional arguments
rather than as a list; the detector read only the list spelling, so the site
was absent from the population rather than misclassified in it -- a register
answering `ok` about a call it had never seen, which is precisely the defect
class it was written to catch, committed inside the thing catching it. The
runner set is derived from each file's own call graph now, not from a list of
helper names, because the list was what made the miss possible.

**What "owned" means, and what it deliberately refuses.** The question is
#1246's -- which argument names a directory, and who knows what that directory
is allowed to be. So ownership is proved, never assumed: every non-literal part
of the expression must trace back to a call that *made* a directory. A path
joined against a value the function was handed is UNOWNED even when the other
half is a `mkdtemp`, because an absolute right-hand operand discards the left --
which is exactly how #1246 walked out of its intended tree.
"""

import ast
from pathlib import Path

from _repo_walk import REPO_ROOT as ROOT
from _repo_walk import repo_python_files

TESTS = Path(__file__).resolve().parent

#: Calls that hand back a directory the caller now owns.
OWNERS = ("mkdtemp", "TemporaryDirectory", "mkstemp", "NamedTemporaryFile")

#: Calls that re-spell a path without changing which directory it names, so
#: ownership passes straight through them.
PASSTHROUGH = ("str", "Path", "dirname", "abspath", "realpath", "resolve",
               "normpath", "fspath")

#: pytest hands these out already made and reaps them itself.
FRAMEWORK = ("tmp_path", "tmp_path_factory", "tmpdir", "tmpdir_factory")

OWNED = "OWNED: made by this file, or handed over by pytest"
GIT = "GIT: a worktree removal of a path this code did not compose"
UNOWNED = "UNOWNED"

#: Callables that spawn an argv on their own. Anything else holding the same
#: list is asserting about a command, not running one.
SPAWNERS = ("run", "Popen", "call", "check_call", "check_output", "system")


def _runners(module):
    """Names in this file that reach a subprocess, derived rather than listed.

    A hardcoded list of helper names is the wrong shape and was measurably
    wrong: it named `_git`, `_git_rc` and `_run`, and the first pass of this
    register still missed the executed `git worktree remove` at
    `tests/test_branch_worktree_locale_850.py:218`, because that helper takes
    its words as *positional arguments* rather than a list. Deriving the set --
    a function is a runner if its body reaches `subprocess`, transitively --
    means a helper named anything at all is still seen.
    """
    # One walk builds the call graph; the fixed point then runs over names
    # only. Re-walking every def on every round instead cost 4.5s a sweep on
    # this tree, on a file filed under `lane-ci-cost`.
    calls = {}
    for node in ast.walk(module):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        names = calls.setdefault(node.name, set())
        for call in ast.walk(node):
            if not isinstance(call, ast.Call):
                continue
            func = call.func
            if isinstance(func, ast.Attribute):
                # `subprocess.run(...)` spawns; `mock.run(...)` does not, and
                # neither does a `.run()` on something we cannot see.
                if func.attr in SPAWNERS and "subprocess" in ast.unparse(func.value):
                    names.add(func.attr)
            elif isinstance(func, ast.Name):
                names.add(func.id)
    runners = set(SPAWNERS)
    for _round in range(len(calls) + 1):
        grown = set(name for name, called in calls.items()
                    if name not in runners and called & runners)
        if not grown:
            break
        runners |= grown
    return runners


def _scopes(module, node):
    """Every def/class enclosing `node`, outermost first."""
    return sorted(
        (n for n in ast.walk(module)
         if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef))
         and n.lineno <= node.lineno <= (n.end_lineno or n.lineno)),
        key=lambda n: n.lineno)


#: `id(scope)` -> `{name: [bound expression, ...]}`, for the file being read
#: right now and no other. Without it every lookup re-walked the scope and
#: re-`unparse`d every assignment target in it, which cost 13s a sweep.
#:
#: **Cleared per file, and that is not tidiness.** CPython reuses the `id` of a
#: freed object, and the previous file's tree is freed the moment the next one
#: is parsed -- so a cache that outlived one file could hand a scope another
#: file's bindings, and produce a clean-looking verdict about code it had not
#: read. `_sites_in_source` holds its own module alive for as long as any of
#: these keys can be looked up.
_BINDINGS: dict = {}


def _bindings_in(container, target):
    """Every expression `target` is bound to inside one scope, nested defs included.

    A `for` target is special: `for d in made:` binds `d` to whatever went
    INTO `made`, not to `made`. Resolving it to the container is what made the
    one real teardown loop in this tree read as UNOWNED.
    """
    table = _BINDINGS.get(id(container))
    if table is None:
        table = {}
        for node in ast.walk(container):
            if isinstance(node, ast.Assign):
                for one in node.targets:
                    table.setdefault(ast.unparse(one), []).append(node.value)
            elif isinstance(node, ast.AnnAssign) and node.value is not None:
                table.setdefault(ast.unparse(node.target), []).append(node.value)
            elif isinstance(node, ast.withitem) and node.optional_vars is not None:
                table.setdefault(
                    ast.unparse(node.optional_vars), []).append(node.context_expr)
            elif isinstance(node, ast.For):
                key = ast.unparse(node.target)
                if isinstance(node.iter, ast.Name):
                    table.setdefault(key, []).extend(
                        _pushed_into(container, node.iter.id))
                else:
                    table.setdefault(key, []).append(node.iter)
        _BINDINGS[id(container)] = table
    return table.get(target, [])


def _pushed_into(container, name):
    """Values appended to the list `name` -- how a teardown loop gets its paths."""
    return [node.args[0] for node in ast.walk(container)
            if isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and node.func.attr in ("append", "add")
            and ast.unparse(node.func.value) == name
            and node.args]


def _sources(module, scopes, target):
    """Bindings of `target` from the nearest scope that has any.

    Innermost first, stopping at the first scope that binds it. Falling through
    to the module for a name an enclosing function already binds is not a
    widening but a wrong answer: `tmp` is a local in eight separate functions
    of `test_git_checkout_rebase_state_900.py`, and pooling all eight made a
    teardown that only ever removes its own `mkdtemp` read as UNOWNED.
    """
    for container in list(reversed(list(scopes))) + [module]:
        found = _bindings_in(container, target)
        if found:
            return found
    return []


def _classes(module):
    """`name -> ClassDef` for every class defined in this file."""
    return dict((n.name, n) for n in ast.walk(module)
                if isinstance(n, ast.ClassDef))


def _receiver_class(receiver, module, scopes):
    """The ClassDef whose instance `receiver` is, or None when it cannot be told.

    `self` is the enclosing class. Anything else has to have been built by a
    visible constructor call -- `box = _Repo()`. Nothing else counts: guessing
    is what produced the false OWNED this exists to stop.
    """
    classes = _classes(module)
    if isinstance(receiver, ast.Name) and receiver.id == "self":
        for node in reversed(list(scopes)):
            if isinstance(node, ast.ClassDef):
                return node
        return None
    for bound in _sources(module, scopes, ast.unparse(receiver)):
        if (isinstance(bound, ast.Call) and isinstance(bound.func, ast.Name)
                and bound.func.id in classes):
            return classes[bound.func.id]
    return None


def _is_owned(expr, module, scopes, depth=0, seen=()):
    """Does `expr` name a directory this file made?

    A string literal is never owned. That is the whole difference between this
    and a classifier that certifies `ROOT = "/somewhere"`: a hardcoded path is
    a claim about the world, not a directory we created. Literals are allowed
    only as the *later* operands of a join under a root that is already ours,
    which is the one place they cannot redirect anything.
    """
    if depth > 10:
        return False
    if isinstance(expr, ast.Constant):
        return False
    if isinstance(expr, (ast.List, ast.Tuple)):
        return bool(expr.elts) and all(
            _is_owned(e, module, scopes, depth + 1, seen) for e in expr.elts)
    if isinstance(expr, ast.JoinedStr):
        # No site composes a removal target with an f-string. Refusing the
        # shape outright is the safe direction: `f"/etc/{ours}"` is not ours,
        # and telling that from `f"{ours}/sub"` needs more than this walk.
        return False
    if isinstance(expr, ast.BinOp):
        # `Path(mkdtemp()) / "sub"` -- the left operand carries the ownership
        # and the right must be a literal, because `Path(a) / b` with an
        # absolute `b` discards `a` exactly as `os.path.join` does (#1246).
        return (_is_owned(expr.left, module, scopes, depth + 1, seen)
                and isinstance(expr.right, ast.Constant))
    if isinstance(expr, ast.Subscript):
        return _is_owned(expr.value, module, scopes, depth + 1, seen)
    if isinstance(expr, ast.Call):
        func = expr.func
        name = (func.attr if isinstance(func, ast.Attribute)
                else func.id if isinstance(func, ast.Name) else "")
        if name in OWNERS:
            return True
        args = list(expr.args) or (
            [func.value] if isinstance(func, ast.Attribute) else [])
        if not args:
            return False
        if name == "join":
            # Only the first operand can be ours; every later one must be a
            # literal. A variable there is UNOWNED however innocent it looks,
            # because one absolute value is all it takes to leave the tree.
            return (_is_owned(args[0], module, scopes, depth + 1, seen)
                    and all(isinstance(a, ast.Constant) for a in args[1:]))
        if name in PASSTHROUGH:
            return _is_owned(args[0], module, scopes, depth + 1, seen)
        return False
    if isinstance(expr, (ast.Name, ast.Attribute)):
        key = ast.unparse(expr)
        if isinstance(expr, ast.Name) and expr.id in FRAMEWORK:
            return True
        sources = _sources(module, scopes, key)
        if isinstance(expr, ast.Attribute) and not sources:
            # `box.tmp` where `_Repo.__init__` set `self.tmp = mkdtemp(...)`.
            #
            # Resolved through the receiver's *class*, never by looking for
            # `self.<attr>` anywhere in the file. The loose version certified
            # `box.tmp` for any `box` at all as soon as some unrelated class in
            # the same module happened to assign `self.tmp = mkdtemp()` -- a
            # false OWNED, which is the only direction of error that matters
            # here, since it is the one that lets an unsafe removal through.
            owner = _receiver_class(expr.value, module, scopes)
            if owner is None:
                return False
            sources = _bindings_in(owner, "self." + expr.attr)
        sources = [s for s in sources
                   if ast.unparse(s) not in seen + (key,)
                   and not (isinstance(s, (ast.List, ast.Tuple)) and not s.elts)]
        if not sources:
            return False
        return all(_is_owned(s, module, scopes, depth + 1, seen + (key,))
                   for s in sources)
    return False


def _removal_target(node, runners):
    """The directory a call would destroy, or `(None, None)` if it destroys none.

    Returns `(expr, kind)`. `kind` is `"worktree"` for `git worktree remove`,
    which may or may not be composed by the caller -- `_sites_in_source`
    decides that by asking the same ownership question it asks of everything
    else, and only an unowned one is exempted.
    """
    func = node.func
    name = (func.attr if isinstance(func, ast.Attribute)
            else func.id if isinstance(func, ast.Name) else None)
    if name == "rmtree" and node.args:
        return node.args[0], "call"
    if name in ("rmdir", "removedirs"):
        if node.args:
            return node.args[0], "call"
        if isinstance(func, ast.Attribute):
            return func.value, "call"
        return None, None
    # Only a call that *runs* an argv removes anything. A test asserting on
    # `["worktree", "remove", path]` is reading a receipt, and a register that
    # counted it would report removals nobody performs.
    if name not in runners or not node.args:
        return None, None
    # Two spellings, and reading only the first is what hid a real site: a
    # helper may take the argv as a list (`_git_rc(["worktree", "remove", p])`)
    # or as its own positional arguments (`_git("worktree", "remove", p)`).
    if isinstance(node.args[0], (ast.List, ast.Tuple)):
        elts = node.args[0].elts
    else:
        elts = list(node.args)
    if any(isinstance(e, ast.Starred) for e in elts):
        # `["git", *args]` -- the words are not in this file's AST. Almost all
        # of these are the generic helper definitions whose *callers* carry the
        # verb, and those callers are read above.
        return None, None
    words = [e.value for e in elts
             if isinstance(e, ast.Constant) and isinstance(e.value, str)]
    if not words:
        return None, None
    operands = [e for e in elts
                if not (isinstance(e, ast.Constant)
                        and isinstance(e.value, str)
                        and e.value.startswith("-"))]
    if words[0] == "rm" and any(
            w.startswith("-") and set(w[1:]) & set("rR") for w in words[1:]):
        return (operands[1] if len(operands) > 1 else None), "call"
    if "worktree" in words and "remove" in words:
        return (operands[-1] if operands else None), "worktree"
    return None, None


def _sites_in_source(rel, source, found=None):
    """One file's sites. Split out so the classifier can be run on strings."""
    found = {} if found is None else found
    _BINDINGS.clear()
    module = ast.parse(source)
    runners = _runners(module)
    for node in ast.walk(module):
        if not isinstance(node, ast.Call):
            continue
        target, kind = _removal_target(node, runners)
        if target is None:
            continue
        scopes = _scopes(module, node)
        if _is_owned(target, module, scopes):
            # A `git worktree remove` of a path the test built itself is as
            # owned as any other removal, and gets no exemption for its verb.
            mechanism = OWNED
        elif kind == "worktree":
            mechanism = GIT
        else:
            mechanism = UNOWNED
        key = "{0}::{1}".format(
            rel, ".".join(n.name for n in scopes) or "<module>")
        found.setdefault(key, []).append((node.lineno, mechanism))
    return found


#: One sweep per process. Six tests ask the same question of the same tree,
#: and this file is in the `lane-ci-cost` issue's own lane.
_SWEEP: list = []


def _call_sites():
    """`(sites, unreadable)` for the whole tree.

    A file this walk cannot parse is *returned*, never skipped. Skipping it
    would subtract a file from the population and leave the answer looking
    exactly like a file with no removals in it -- the absence-read-as-absence
    shape this register exists to keep out of the suite.

    **Every `.py` file is parsed, and a byte prefilter was tried and removed.**
    Skipping files whose bytes hold none of `rmtree` / `rmdir` / `worktree` /
    `"rm"` cut a sweep from 21s to 8s. But a prefilter is a grep, and this
    register exists because a grep over this tree reads as an inventory and is
    not one -- so it needs a test that parses everything and demands the same
    answer, which costs the 21s back plus the 8s. Measured, the fast path plus
    its proof was slower than never taking it.
    """
    if _SWEEP:
        return _SWEEP[0]
    found = {}
    unreadable = []
    for path in repo_python_files():
        rel = path.relative_to(ROOT).as_posix()
        try:
            _sites_in_source(rel, path.read_text(encoding="utf-8"), found)
        except (OSError, UnicodeDecodeError, SyntaxError, ValueError) as exc:
            unreadable.append((rel, type(exc).__name__))
    _SWEEP.append((found, unreadable))
    return found, unreadable


def _mechanisms():
    """`key` -> the one mechanism covering every removal under it."""
    out = {}
    for key, sites in _call_sites()[0].items():
        kinds = set(mech for _line, mech in sites)
        out[key] = kinds.pop() if len(kinds) == 1 else "MIXED: " + repr(sorted(kinds))
    return out


#: Every call in this tree that can remove a directory, and what proves the
#: directory was its to remove. Keyed by `path::enclosing def`, not by line
#: number, so an unrelated edit above does not make it stale.
REGISTER = {
    # The only directory removal in product code. The path is not composed
    # here at all -- git reported it -- and the arm ahead of it refuses on
    # three separate reads before it fires (#1280, #1290).
    'presets/github/pr_merge.py::_cleanup_worktree': GIT,

    # An executed `git worktree remove`, and the site the first cut of this
    # register did not see: its helper takes the argv words as positional
    # arguments rather than as a list. The path is the fixture's `tmp_path`.
    'tests/test_branch_worktree_locale_850.py::test_a_branch_checked_out_nowhere_still_warns_and_still_advises': OWNED,

    'tests/test_git_checkout_pathspec_756.py::repo': OWNED,
    'tests/test_git_checkout_rebase_state_900.py::repo': OWNED,
    'tests/test_git_checkout_recovery_649.py::remote_factory': OWNED,
    'tests/test_git_mr_lookup_948.py::test_a_git_that_cannot_be_spawned_is_an_unknown_not_a_traceback': OWNED,
    'tests/test_git_push_budget_1530.py::_Sandbox.close': OWNED,
    'tests/test_git_push_budget_ceilings_1659_1647_1649.py::_Sandbox.close': OWNED,
    'tests/test_git_push_budget_deadline_1615_1617.py::_Sandbox.close': OWNED,
    'tests/test_git_push_budget_from_config_1631.py::_Sandbox.close': OWNED,
    'tests/test_git_push_first_upstream_354.py::FirstUpstreamRebaseTest.tearDown': OWNED,
    'tests/test_git_push_force_discard_655.py::_Sandbox.close': OWNED,
    'tests/test_git_push_hazards_640_642_647.py::_Sandbox.close': OWNED,
    'tests/test_git_push_hook_text_nff_641.py::_Sandbox.close': OWNED,
    'tests/test_git_push_mismatched_upstream_787.py::MismatchedUpstreamTest.tearDown': OWNED,
    'tests/test_git_push_post_push_receipt_675.py::_Sandbox.close': OWNED,
    'tests/test_git_push_rebase_route_discloses_hook_1490.py::_Sandbox.close': OWNED,
    'tests/test_git_push_receipt_truthfulness_661_662_663.py::_Sandbox.close': OWNED,
    'tests/test_git_push_relays_hook_output_1448.py::_Sandbox.close': OWNED,
    'tests/test_git_push_remote_resolution_656.py::_Box.close': OWNED,
    'tests/test_git_push_set_upstream_879.py::InheritedUpstreamTest.tearDown': OWNED,
    'tests/test_git_push_set_upstream_879.py::MatchingUpstreamTest.tearDown': OWNED,
    'tests/test_git_worktrees_unpushed_1496.py::_Sandbox.close': OWNED,
    'tests/test_git_worktrees_upstream_remote_1525.py::_Sandbox.close': OWNED,
    'tests/test_kevin_2026_05_17.py::test_paste_op_creates_missing_file_and_parent': OWNED,
    'tests/test_mcp_daemon_dedup_451.py::runtime': OWNED,
    'tests/test_notifiers_claude_channel_550.py::sock_dir': OWNED,
    'tests/test_notifiers_claude_channel_554.py::Channel.close': OWNED,
    'tests/test_vim_kevin_fixes.py::_cleanup_persist': OWNED,
    'tests/test_vim_kevin_fixes.py::test_undo_cross_call': OWNED,
    'validators/gitleaks/gitleaks.py::main': OWNED,
}


def test_the_register_is_the_tree() -> None:
    """Six claims about the sweep, and one sweep to answer all six.

    They are one test rather than six because `pyproject.toml` runs the suite
    under `-n auto`, whose default `--dist load` scatters the tests of a file
    across workers -- and each worker that gets one pays its own full-tree
    sweep, ~20s of `ast.parse` over 940 files. Six separate tests were six
    sweeps. (An `xdist_group` mark does not fix that: it is honoured only
    under `--dist loadgroup`, which this repo does not set.) The order runs
    outward from "the population is whole", which is also the order a reader
    wants to learn about failures in.
    """
    live = _mechanisms()
    _sites, unreadable = _call_sites()

    # 1. The population is only a population if nothing dropped out of it. A
    #    file the walk could not parse is not a file without removals in it.
    assert not unreadable, (
        "these files were counted in no verdict below, so nothing here is "
        "claimed about them: " + repr(unreadable))

    # 2. The load-bearing one, and the answer to #1635's first question. A
    #    site reclassified UNOWNED by a later edit -- a `mkdtemp` swapped for
    #    a path out of the environment, a teardown that starts joining an
    #    argument onto its root -- turns this red on the commit that does it,
    #    not on the run that loses somebody's checkout.
    unowned = sorted(k for k, mech in live.items() if UNOWNED in mech)
    assert not unowned, (
        "these can remove a directory whose provenance is not established: "
        + repr({k: live[k] for k in unowned}))

    # 3. A new removal must be classified here before it can be merged.
    missing = sorted(k for k in live if k not in REGISTER)
    assert not missing, (
        "directory-removal sites with no entry in REGISTER -- add them with "
        "the mechanism that proves each owns what it deletes: "
        + repr({k: live[k] for k in missing}))

    # 4. An entry with no call site left is a stale claim, which is the shape
    #    this repo keeps mistaking for a true one.
    stale = sorted(k for k in REGISTER if k not in live)
    assert not stale, "REGISTER entries with no call site left: " + repr(stale)

    # 5. The label is re-derived, never trusted.
    drifted = dict((k, (REGISTER[k], live[k])) for k in REGISTER
                   if k in live and REGISTER[k] != live[k])
    assert not drifted, (
        "the mechanism recorded here is no longer the mechanism in the code "
        "(recorded, actual): " + repr(drifted))

    # 6. `GIT` is an exemption, so the set that holds it is pinned by name. A
    #    `git worktree remove` is the one removal whose path can legitimately
    #    come from outside -- git reported it. That is also a hole big enough
    #    to hide a second one in, so it is not a category anyone joins
    #    quietly: a new unowned worktree removal has to argue for itself here.
    exempt = sorted(k for k, mech in live.items() if mech == GIT)
    assert exempt == ['presets/github/pr_merge.py::_cleanup_worktree'], exempt


def test_the_walk_still_reaches_every_subsystem_that_holds_a_site() -> None:
    """The population is not allowed to quietly shrink.

    The sweep no longer owns its own exclusion list -- it asks
    `tests/_repo_walk.py`, and that module is shared with two other guards and
    can change under this one. So the claim is checked here rather than
    assumed: every directory the register names a site in must still be
    reachable, and the file holding each site must still be in the walk.

    This is what the first cut spelled as "no name in my own `SKIP_DIRS` is a
    directory of ours", which was both weaker and, as CI found on its first
    run, wrong about `build/`.
    """
    reached = set(p.relative_to(ROOT).as_posix() for p in repo_python_files())
    named = sorted(set(key.split("::")[0] for key in REGISTER))
    missing = [rel for rel in named if rel not in reached]
    assert not missing, (
        "the walk no longer reaches files this register has sites in, so "
        "those sites are in no verdict above: " + repr(missing))

    subsystems = sorted(set(rel.split("/")[0] for rel in named))
    assert subsystems == ["presets", "tests", "validators"], subsystems


def test_the_core_removes_no_directory_at_all() -> None:
    """`_supertool.py` is the file every op runs through, and it must stay
    incapable of removing a directory. It unlinks cache entries and its own
    write-temp files; it has never had a `shutil.rmtree`, and a checker that
    only counted test-side sites would not notice one arriving."""
    sites = _sites_in_source(
        "_supertool.py", (ROOT / "_supertool.py").read_text(encoding="utf-8"))
    assert not sites, "the core gained a directory removal: " + repr(sites)


def test_the_classifier_refuses_a_path_it_cannot_prove_ownership_of() -> None:
    """Without this the register is a list, not a claim.

    Each source below is a string, so none of these calls exists in this
    module's own AST -- which is the same reason the grep this file replaces
    could not tell a payload from a call site.
    """
    nl = chr(10)

    def mech(*body):
        src = nl.join(body) + nl
        sites = _sites_in_source("tests/synthetic.py", src)
        return list(sites.values())[0][0][1]

    assert mech("import shutil, tempfile",
                "def t():",
                "    d = tempfile.mkdtemp()",
                "    shutil.rmtree(d)") == OWNED

    assert mech("import shutil",
                "def t(tmp_path):",
                "    shutil.rmtree(tmp_path)") == OWNED

    assert mech("import shutil",
                "ROOT = '/somewhere'",
                "def t():",
                "    shutil.rmtree(ROOT)") == UNOWNED, (
        "a module constant is not a directory this file made")

    assert mech("import shutil, os, tempfile",
                "def t(name):",
                "    d = tempfile.mkdtemp()",
                "    shutil.rmtree(os.path.join(d, name))") == UNOWNED, (
        "an argument joined onto our own root was certified -- an absolute "
        "right-hand operand discards the left, which is how #1246 escaped")

    assert mech("import shutil, os, tempfile",
                "def t():",
                "    d = tempfile.mkdtemp()",
                "    shutil.rmtree(os.path.join(d, 'sub'))") == OWNED, (
        "a literal component under our own root is still ours")

    assert mech("import shutil, tempfile",
                "def t(where):",
                "    d = tempfile.mkdtemp()",
                "    d = where",
                "    shutil.rmtree(d)") == UNOWNED, (
        "one owning assignment does not certify a name that is also bound to "
        "something we were handed")

    assert mech("import shutil, tempfile",
                "class Thing:",
                "    def __init__(self):",
                "        self.tmp = tempfile.mkdtemp()",
                "def cleanup(box):",
                "    shutil.rmtree(box.tmp)") == UNOWNED, (
        "`box` is whatever the caller passed. An unrelated class in the same "
        "file assigning `self.tmp = mkdtemp()` certified it until the receiver "
        "was resolved through its own class")

    assert mech("import shutil, tempfile",
                "class Repo:",
                "    def __init__(self):",
                "        self.tmp = tempfile.mkdtemp()",
                "def cleanup():",
                "    box = Repo()",
                "    shutil.rmtree(box.tmp)") == OWNED, (
        "a receiver built by a visible constructor does carry its class's "
        "ownership, and tightening the rule above must not have cost that")

    assert mech("import subprocess",
                "def _sh(*args, cwd):",
                "    subprocess.run(['git', *args], cwd=cwd)",
                "def t(tmp_path):",
                "    _sh('worktree', 'remove', str(tmp_path), cwd='.')") == OWNED, (
        "a helper taking its argv as positional arguments executes a real "
        "removal, and reading only the list spelling hid one in this tree")

    assert not _sites_in_source(
        "tests/synthetic.py",
        "def t():" + nl + "    " + chr(39) * 3 + "mentions shutil.rmtree(ROOT)"
        + chr(39) * 3 + nl + "    return 1" + nl), (
        "a docstring naming a removal was read as a call site")
