"""#1783 items 1-3: the pip route, the exists/open race one directory up,
and the else arm that asserts a specific claim about an unreached verdict.

Item 1 -- the pip route ships neither `.supertool.json` nor `presets/`
(`py-modules = ["supertool", "_supertool"]`, no packages, no `MANIFEST.in`),
so `_shipped_config()` found nothing and every `help:OP` for an
undocumented-by-project op printed a false "incomplete install" sentence about
a route the README endorses. Every declarative packaging route that could
carry a data file there was tried and rejected in the issue's own comment
thread -- `package-data`, `MANIFEST.in` + `include-package-data`,
`data-files` -- so the fix ships `_shipped_reference.py`, an importable
module carrying only the `builtin-ops` block, generated by
`.github/scripts/generate_shipped_reference.py`. This test builds the real
wheel and lists its contents -- the issue's own instruction, not a re-read of
the manifest.

Item 2 -- `_shipped_config()` used `os.path.exists(path)` as a pre-check
before `open()`. #1781 fixed the file-level case (`chmod 000` on the file
itself); the same defect survives one directory up, where an unreadable
*directory* makes `os.path.exists` swallow `EACCES` and return `False`, so a
reference that is present and readable reports as "not there" -- the exact
false sentence #1781 was filed to remove, one level up. The fix drops the
`exists()` pre-check, opens unconditionally, and branches on
`FileNotFoundError` (genuinely absent) versus any other `OSError`
(unreadable).

Item 3 -- the final `else` arm in the "no documented help" refusal caught
every verdict that was not `"unreadable"` or `"absent"`, including `"read"`
and any future fourth value, and asserted "was read and does not document it
either" even for a value nobody has produced. The fix makes `"read"` an
explicit `elif` and gives the real `else` an honest "verdict unknown"
sentence.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import venv
import zipfile
from pathlib import Path

import pytest

import supertool

REPO_ROOT = Path(__file__).parent.parent


# ---------------------------------------------------------------------------
# Item 1 -- the pip route
# ---------------------------------------------------------------------------


@pytest.mark.slow
def test_the_built_wheel_ships_a_shipped_reference_module(tmp_path: Path) -> None:
    """Build the actual wheel and list it -- the issue's own instruction.

    Before the fix this wheel contained exactly `_supertool.py`, `supertool.py`
    and the dist-info directory. The fix must add `_shipped_reference.py`
    without removing or renaming either of the other two.
    """
    venv_dir = tmp_path / "buildenv"
    venv.EnvBuilder(with_pip=True).create(venv_dir)
    bin_dir = venv_dir / ("Scripts" if sys.platform == "win32" else "bin")
    venv_python = bin_dir / ("python.exe" if sys.platform == "win32" else "python")

    subprocess.run(
        [str(venv_python), "-m", "pip", "install", "build"],
        check=True, capture_output=True, encoding="utf-8", errors="replace",
    )

    out_dir = tmp_path / "dist"
    build = subprocess.run(
        [str(venv_python), "-m", "build", "--wheel", "--outdir", str(out_dir),
         str(REPO_ROOT)],
        capture_output=True, encoding="utf-8", errors="replace",
    )
    assert build.returncode == 0, (
        "wheel build failed\nstdout: " + build.stdout + "\nstderr: " + build.stderr
    )

    wheels = list(out_dir.glob("*.whl"))
    assert len(wheels) == 1, f"expected exactly one wheel, found {wheels}"

    with zipfile.ZipFile(wheels[0]) as zf:
        names = {Path(n).name for n in zf.namelist()}

    assert "_shipped_reference.py" in names, (
        f"the wheel does not ship _shipped_reference.py -- pip installs "
        f"still carry no builtin-ops reference (#1783). Wheel contents: "
        f"{sorted(names)}"
    )
    assert "_supertool.py" in names and "supertool.py" in names, (
        f"the fix must not drop either existing module: {sorted(names)}"
    )


def test_generated_reference_is_not_stale() -> None:
    """The generator's output and the checked-in file must agree.

    A `.supertool.json` edited without re-running the generator is exactly
    the drift this guards: pip installs would keep documenting a `builtin-ops`
    block this repo no longer has.
    """
    import importlib.util

    spec = importlib.util.spec_from_file_location(
        "_generate_shipped_reference_1783",
        REPO_ROOT / ".github" / "scripts" / "generate_shipped_reference.py")
    gen = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(gen)

    expected = gen.render()
    actual = (REPO_ROOT / "_shipped_reference.py").read_text(encoding="utf-8")
    assert actual == expected, (
        "_shipped_reference.py is stale -- run "
        "`python3 .github/scripts/generate_shipped_reference.py` and commit "
        "the result."
    )


def test_generator_writes_with_explicit_lf_newline(tmp_path: Path,
                                                     monkeypatch: pytest.MonkeyPatch) -> None:
    """`main()`'s `open(out_path, "w", encoding="utf-8")` has no `newline=`,
    so on a Windows contributor's machine text-mode write translates every
    newline in the rendered string to `os.linesep` (CRLF) -- invisible on
    macOS/Linux where `os.linesep` already is a bare newline, and not caught
    by `test_generated_reference_is_not_stale` either: that test reads the
    written file back with `Path.read_text()`, which applies universal-
    newline translation and silently converts the CRLF back before the
    comparison, so the test passes even though the bytes just written to
    disk differ from what a non-Windows run produces from the same source
    data (#1783 review, oss:auditor). #1783's own comment thread already
    established this repo has no `.gitattributes` pinning this file to LF."""
    import importlib.util
    import unittest.mock

    spec = importlib.util.spec_from_file_location(
        "_generate_shipped_reference_1783_newline",
        REPO_ROOT / ".github" / "scripts" / "generate_shipped_reference.py")
    gen = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(gen)

    monkeypatch.setattr(gen, "REPO_ROOT", str(REPO_ROOT))
    real_open = open
    captured = {}

    def spy_open(path, *args, **kwargs):
        if str(path) == os.path.join(str(REPO_ROOT), "_shipped_reference.py"):
            captured["newline"] = kwargs.get("newline", "sentinel-not-passed")
            return real_open(os.devnull, "w", encoding="utf-8")
        return real_open(path, *args, **kwargs)

    with unittest.mock.patch("builtins.open", side_effect=spy_open):
        gen.main()

    assert captured, "main() never opened _shipped_reference.py for writing"
    assert captured["newline"] == "\n", (
        f"main() wrote _shipped_reference.py without pinning newline to a "
        f"bare newline (got {captured['newline']!r}) -- on Windows this "
        f"writes CRLF via the platform default os.linesep, a line-ending-"
        f"only diff on a file meant to be byte-reproducible across the "
        f"whole matrix"
    )


def test_generated_reference_carries_builtin_ops_only_not_the_whole_file() -> None:
    """The `ops` section (preset config overrides) must never be folded in --
    it documents presets/ the pip route does not ship (#1783's own comment)."""
    import _shipped_reference

    with open(REPO_ROOT / ".supertool.json", encoding="utf-8") as fh:
        project_config = json.load(fh)

    assert _shipped_reference.BUILTIN_OPS == project_config["builtin-ops"]
    assert not hasattr(_shipped_reference, "OPS")
    source = (REPO_ROOT / "_shipped_reference.py").read_text(encoding="utf-8")
    # None of the eight preset-override op names should appear as a JSON key
    # -- they only exist in `.supertool.json`'s `ops` section.
    for op_name in project_config.get("ops", {}):
        assert f'"{op_name}":' not in source, (
            f"{op_name!r} is a preset-config override from the `ops` "
            f"section and should not be in the generated builtin-ops module"
        )


def test_pyproject_declares_the_shipped_reference_module() -> None:
    try:
        import tomllib
    except ModuleNotFoundError:  # pragma: no cover - py3.9/3.10
        pytest.skip("tomllib requires Python 3.11+")
    with open(REPO_ROOT / "pyproject.toml", "rb") as fh:
        cfg = tomllib.load(fh)
    declared = set(cfg["tool"]["setuptools"]["py-modules"])
    assert "_shipped_reference" in declared


def _install_pip_shape(directory: Path) -> None:
    """Copy the real `_shipped_reference.py` beside a bare directory --
    the pip route's actual layout: `.supertool.json` absent, the generated
    module present, both beside the same `_supertool.py`."""
    import shutil
    shutil.copy2(REPO_ROOT / "_shipped_reference.py",
                 directory / "_shipped_reference.py")


def test_shipped_config_falls_back_to_the_module_when_the_json_is_absent(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The pip-route shape: no `.supertool.json` beside the running module,
    but `_shipped_reference.py` sitting right there instead."""
    _install_pip_shape(tmp_path)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG", None)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_STATE", None)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_DIR", str(tmp_path))

    config = supertool._shipped_config()
    assert config.get("builtin-ops"), (
        "no .supertool.json in this directory, and _shipped_reference.py "
        "should have been used as the fallback, but builtin-ops is empty"
    )
    assert supertool._SHIPPED_CONFIG_STATE == "read", (
        f"expected the fallback to count as a real read, got "
        f"{supertool._SHIPPED_CONFIG_STATE!r}"
    )


def test_shipped_config_reports_unreadable_when_the_fallback_module_is_broken(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """A `_shipped_reference.py` that exists but fails to load -- unreadable
    permissions, or a syntax error in a hand-damaged install -- must not
    silently collapse back to `absent`. #1783 review (Explore/oss:auditor):
    the fallback's `except (OSError, ImportError, SyntaxError, ValueError):
    pass` left `_SHIPPED_CONFIG_STATE` unchanged at `absent` for a reference
    that is present but broken, reintroducing the exact defect item 2 of
    this same issue closed for `.supertool.json` -- one file over."""
    (tmp_path / "_shipped_reference.py").write_text(
        "this is not valid python syntax :::", encoding="utf-8")
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG", None)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_STATE", None)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_DIR", str(tmp_path))

    config = supertool._shipped_config()
    assert config == {} or not config.get("builtin-ops")
    assert supertool._SHIPPED_CONFIG_STATE == "unreadable", (
        f"a present-but-broken fallback module was reported as "
        f"{supertool._SHIPPED_CONFIG_STATE!r}, indistinguishable from a "
        f"genuinely absent install"
    )


def test_shipped_config_stays_absent_with_neither_file_nor_module(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """The genuinely broken install: neither `.supertool.json` nor
    `_shipped_reference.py` beside the running module. Must not silently
    find this repo's own `_shipped_reference.py` via `sys.path` instead."""
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG", None)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_STATE", None)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_DIR", str(tmp_path))

    config = supertool._shipped_config()
    assert config == {} or not config.get("builtin-ops")
    assert supertool._SHIPPED_CONFIG_STATE == "absent"


def test_help_for_a_builtin_op_works_on_the_pip_shape(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    """End to end: `help:read` must not print the "incomplete install"
    sentence when the only thing missing is `.supertool.json` itself."""
    _install_pip_shape(tmp_path)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG", None)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_STATE", None)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_DIR", str(tmp_path))
    monkeypatch.setattr(supertool, "_CONFIG", {})
    monkeypatch.setattr(supertool, "_CONFIG_CHECKED", True)
    monkeypatch.setattr(supertool, "_CONFIG_PATH", "/somewhere/else/.supertool.json")

    out = supertool.op_help("read")
    assert "incomplete install" not in out, out
    assert "not there" not in out, out
    assert "read:PATH" in out or "syntax" in out.lower(), out


# ---------------------------------------------------------------------------
# Item 2 -- exists()/open() race one directory up
# ---------------------------------------------------------------------------


@pytest.fixture
def consumer_tree(monkeypatch: pytest.MonkeyPatch):
    monkeypatch.setattr(supertool, "_CONFIG", {})
    monkeypatch.setattr(supertool, "_CONFIG_CHECKED", True)
    monkeypatch.setattr(supertool, "_CONFIG_PATH", "/somewhere/else/.supertool.json")


def _install(directory: Path, monkeypatch: pytest.MonkeyPatch, contents):
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG", None)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_STATE", None)
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_DIR", str(directory))
    path = directory / ".supertool.json"
    if contents is not None:
        path.write_text(contents, encoding="utf-8")
    return path


def test_an_unreadable_install_directory_is_not_reported_as_absent(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch, consumer_tree) -> None:
    """The actual bug: `chmod 000` on the *directory*, with a real, readable
    reference file inside it. `os.path.exists` swallows the resulting
    `EACCES` and returns False, so this used to render byte-identical to a
    genuinely absent install."""
    outer = tmp_path / "outer"
    outer.mkdir()
    inner = outer / "install"
    inner.mkdir()
    _install(inner, monkeypatch,
              json.dumps({"builtin-ops": {"read": {"syntax": "read:PATH"}}}))

    inner.chmod(0o000)
    try:
        try:
            os.listdir(str(inner))
        except OSError:
            pass
        else:
            pytest.skip("this process ignores directory mode bits (root, or "
                        "a platform that does not enforce them); the state "
                        "cannot be built here")
        out = supertool.op_help("read")
    finally:
        inner.chmod(0o755)

    assert "not there" not in out and "absent" not in out.lower(), (
        f"an unreadable directory containing a real reference was reported "
        f"as absent, the exact defect #1781 fixed one level down: {out!r}"
    )
    assert "UNKNOWN" in out, out


# The five shapes the issue names, run together as positive controls proving
# the fix above did not just move the bug -- absent, unreadable file, scalar
# JSON, a good config, and the unreadable-directory case above.


def test_shape_absent(tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
                       consumer_tree) -> None:
    _install(tmp_path, monkeypatch, None)
    out = supertool.op_help("read")
    assert "not there" in out or "absent" in out
    assert "UNKNOWN" not in out


def test_shape_unreadable_file(tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
                                consumer_tree) -> None:
    path = _install(tmp_path, monkeypatch,
                    json.dumps({"builtin-ops": {"read": {"syntax": "read:PATH"}}}))
    path.chmod(0o000)
    try:
        try:
            path.read_text(encoding="utf-8")
        except OSError:
            pass
        else:
            pytest.skip("this process can read a 0o000 file; the state "
                        "cannot be built here")
        out = supertool.op_help("read")
    finally:
        path.chmod(0o644)
    assert "UNKNOWN" in out
    assert "not there" not in out


def test_shape_scalar_json(tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
                            consumer_tree) -> None:
    _install(tmp_path, monkeypatch, json.dumps(["a list, not an object"]))
    out = supertool.op_help("read")
    assert "UNKNOWN" in out


def test_shape_good_config(tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
                            consumer_tree) -> None:
    _install(tmp_path, monkeypatch,
              json.dumps({"builtin-ops": {"read": {"syntax": "read:PATH"}}}))
    out = supertool.op_help("read")
    assert "read:PATH" in out


# ---------------------------------------------------------------------------
# Item 3 -- the else arm on an unreached verdict
# ---------------------------------------------------------------------------


def test_an_unexpected_verdict_is_reported_as_unknown_not_as_read(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch, consumer_tree) -> None:
    """Construct the unreached fourth state directly, as the issue's own
    reproduction did: nothing in the tree ever sets `_SHIPPED_CONFIG_STATE`
    to anything but `read` / `absent` / `unreadable`, so this state can only
    be built by hand."""
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG", {})
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_STATE", "some-future-state")
    monkeypatch.setattr(supertool, "_SHIPPED_CONFIG_DIR", str(tmp_path))

    out = supertool.op_help("read")
    assert "was read and does not document" not in out, (
        f"an unrecognised verdict was asserted as though it were the "
        f"definite 'read' case: {out!r}"
    )
    assert "unknown" in out.lower(), out


def test_the_read_verdict_still_says_the_true_thing(
        tmp_path: Path, monkeypatch: pytest.MonkeyPatch, consumer_tree) -> None:
    """The positive control for item 3: the real `read` case must keep
    saying its true sentence once it becomes an explicit `elif`."""
    _install(tmp_path, monkeypatch, json.dumps({"builtin-ops": {}}))
    out = supertool.op_help("read")
    assert "was read and does not document" in out
    assert "unknown" not in out.lower()
